name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.DEVELOPOMP_PAT }}

      - name: Build project
        continue-on-error: true
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customImage: "unityci/editor:ubuntu-2021.3.37f1-webgl-3"
          targetPlatform: WebGL

      # Output: Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL
          path: WebGL

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebGL
          path: .

      - name: Move contents of web/ out to pwd
        run: |
          mv ./WebGL/index.html index.html

          rm -rf Build/
          mkdir Build/
          mv ./WebGL/Build/* Build/

          rm -rf TemplateData/
          mkdir TemplateData/
          mv ./WebGL/TemplateData/* TemplateData/

          rm -rf WebGL

      - name: Deploy
        run: |
          # learn more about github action bot email address: https://github.com/orgs/community/discussions/26560#discussioncomment-3252339
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: update demo"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEVELOPOMP_PAT }}
          branch: gh-pages
